/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { RedEnvelopeCoverService } from "../redEnvelopeCover.service";
import { RedEnvelopeCoverCreateInput } from "./RedEnvelopeCoverCreateInput";
import { RedEnvelopeCover } from "./RedEnvelopeCover";
import { RedEnvelopeCoverFindManyArgs } from "./RedEnvelopeCoverFindManyArgs";
import { RedEnvelopeCoverWhereUniqueInput } from "./RedEnvelopeCoverWhereUniqueInput";
import { RedEnvelopeCoverUpdateInput } from "./RedEnvelopeCoverUpdateInput";
import { HistoryFindManyArgs } from "../../history/base/HistoryFindManyArgs";
import { History } from "../../history/base/History";
import { HistoryWhereUniqueInput } from "../../history/base/HistoryWhereUniqueInput";

export class RedEnvelopeCoverControllerBase {
  constructor(protected readonly service: RedEnvelopeCoverService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: RedEnvelopeCover })
  async createRedEnvelopeCover(
    @common.Body() data: RedEnvelopeCoverCreateInput
  ): Promise<RedEnvelopeCover> {
    return await this.service.createRedEnvelopeCover({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [RedEnvelopeCover] })
  @ApiNestedQuery(RedEnvelopeCoverFindManyArgs)
  async redEnvelopeCovers(
    @common.Req() request: Request
  ): Promise<RedEnvelopeCover[]> {
    const args = plainToClass(RedEnvelopeCoverFindManyArgs, request.query);
    return this.service.redEnvelopeCovers({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: RedEnvelopeCover })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async redEnvelopeCover(
    @common.Param() params: RedEnvelopeCoverWhereUniqueInput
  ): Promise<RedEnvelopeCover | null> {
    const result = await this.service.redEnvelopeCover({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: RedEnvelopeCover })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateRedEnvelopeCover(
    @common.Param() params: RedEnvelopeCoverWhereUniqueInput,
    @common.Body() data: RedEnvelopeCoverUpdateInput
  ): Promise<RedEnvelopeCover | null> {
    try {
      return await this.service.updateRedEnvelopeCover({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: RedEnvelopeCover })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteRedEnvelopeCover(
    @common.Param() params: RedEnvelopeCoverWhereUniqueInput
  ): Promise<RedEnvelopeCover | null> {
    try {
      return await this.service.deleteRedEnvelopeCover({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/histories")
  @ApiNestedQuery(HistoryFindManyArgs)
  async findHistories(
    @common.Req() request: Request,
    @common.Param() params: RedEnvelopeCoverWhereUniqueInput
  ): Promise<History[]> {
    const query = plainToClass(HistoryFindManyArgs, request.query);
    const results = await this.service.findHistories(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,

        redEnvelopeCover: {
          select: {
            id: true,
          },
        },

        status: true,
        timeStamp: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/histories")
  async connectHistories(
    @common.Param() params: RedEnvelopeCoverWhereUniqueInput,
    @common.Body() body: HistoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      histories: {
        connect: body,
      },
    };
    await this.service.updateRedEnvelopeCover({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/histories")
  async updateHistories(
    @common.Param() params: RedEnvelopeCoverWhereUniqueInput,
    @common.Body() body: HistoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      histories: {
        set: body,
      },
    };
    await this.service.updateRedEnvelopeCover({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/histories")
  async disconnectHistories(
    @common.Param() params: RedEnvelopeCoverWhereUniqueInput,
    @common.Body() body: HistoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      histories: {
        disconnect: body,
      },
    };
    await this.service.updateRedEnvelopeCover({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Post("/red-envelope-cover/generate")
  @swagger.ApiOkResponse({
    type: String,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async GenerateRedEnvelopeCover(
    @common.Body()
    body: string
  ): Promise<string> {
    return this.service.GenerateRedEnvelopeCover(body);
  }
}
